config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  resources :users
  resources :internship_ops
  resources :internships
  resources :module_sections
  resources :content_tags
  resources :tags
  resources :pages
  resources :contents, only: [:index, :new, :create, :destroy, :edit]
  resources :modules
  get '/contents/middle', to: 'contents#middle'
  get '/contents/callback', to: 'contents#callback'
  root 'module_sections#index' 
  get 'contents/index'
  get 'contents/new'
  get 'contents/create'
  get 'contents/destroy'
  get 'contents/:id', to: 'contents#edit'
  patch 'contents/:id', to: 'contents#update'
  get '/contents', to: 'contents#index'
  patch 'module_sections/:id', to: 'module_sections#update'
  get 'password_management', to: 'password_management#index'
  get 'password_management/:id', to: 'password_management#edit'
  patch 'password_management/:id', to: 'password_management#update'
  get 'users/index', to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
    before_validation(on: :create) do
        self.session_token ||= SecureRandom.hex
    end
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
    validates :title, :description, :content_type, presence: true # Make sure the owner's name is present.
end

app/models/content_tag.rb
class ContentTag < ApplicationRecord
    belongs_to :tag
    belongs_to :page
end

app/models/internship.rb
class Internship < ApplicationRecord
end

app/models/internship_op.rb
class InternshipOp < ApplicationRecord
end

app/models/module.rb
class Module < ApplicationRecord
end

app/models/module_section.rb
class ModuleSection < ApplicationRecord

    has_many :pages

    validates :module_name, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
    has_many :content_tags, dependent: :destroy
    has_many :tags, through: :content_tags

    validates :page_name, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :content_tags, dependent: :destroy
    has_many :pages, through: :content_tag
    validates :tag_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :authentication_keys => [:username]

  enum role: [:member, :admin, :root]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :member
  end
  
end

app/models/video.rb
class Video < ApplicationRecord
end

app/models/video_file.rb
class VideoFile < ApplicationRecord
    before_validation(on: :create) do
        self.session_token ||= SecureRandom.hex
    end
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
    validates :title, :description, presence: true # Make sure the owner's name is present.
    
end

app/models/youtube_session.rb
class YoutubeSession < ApplicationRecord
    before_validation(on: :create) do
        self.session_token ||= SecureRandom.hex
    end
end

app/controllers/module_sections_controller.rb
class ModuleSectionsController < ApplicationController
  before_action :set_module_section, only: %i[ show edit update destroy ]
  before_action :check_admin, only: %i[edit create update destroy]

  # GET /module_sections or /module_sections.json
  def index
    @module_sections = ModuleSection.all
    @pages = Page.all
    @internship_ops = InternshipOp.all
  end

  # GET /module_sections/1 or /module_sections/1.json
  def show
    @pages = Page.all
    @internship_ops = InternshipOp.all
  end

  # GET /module_sections/new
  def new
    @module_section = ModuleSection.new
  end

  # GET /module_sections/1/edit
  def edit
    @module_section = ModuleSection.find(params[:id])
    @pages = Page.all
  end

  # POST /module_sections or /module_sections.json
  def create
    @module_section = ModuleSection.new(module_section_params)
    respond_to do |format|
      if @module_section.save
        format.html { redirect_to module_section_url(@module_section), notice: "Module section was successfully created." }
        format.json { render :show, status: :created, location: @module_section }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @module_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /module_sections/1 or /module_sections/1.json
  def update
    respond_to do |format|
      if @module_section.update(module_section_params)
        format.html { redirect_to module_section_url(@module_section), notice: "Module section was successfully updated." }
        format.json { render :show, status: :ok, location: @module_section }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @module_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /module_sections/1 or /module_sections/1.json
  def destroy
    @module_section.destroy

    respond_to do |format|
      format.html { redirect_to module_sections_url, notice: "Module section was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_module_section
      @module_section = ModuleSection.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def module_section_params
      params.require(:module_section).permit(:module_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/internships_helper.rb
module InternshipsHelper
end

app/helpers/module_sections_helper.rb
module ModuleSectionsHelper
end

app/helpers/modules_helper.rb
module ModulesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/video_files_helper.rb
module VideoFilesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/module_sections/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4><%= link_to 'TAMU-FUSE', module_sections_path %></h4>
      <div class="panel panel-success">
        <div class="panel-heading">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.username %></strong>.|
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
          <% end %>
        </div>
        <div class = "panel-body">
          <%= link_to ' View All Modules', module_sections_path %> 
          <br>
          <%= link_to ' View All Pages', pages_path %> 
          <br>
          <% if current_user.admin? || current_user.root? %>
              <%= link_to ' View All Content', contents_path %> 
              <br>
              <%= link_to ' View All Internships', internship_ops_path %>
            <%else%>
              <%= link_to ' Internships Opportunities ', internship_ops_path %>
          <%end %>
          <% if current_user.root? %>
            <br>
            <%= link_to 'Manage Users', users_index_path %>
          <%end %>
        </div>
      </div>
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to 'New Module', new_module_section_path %></li>
        <li><%= link_to 'New Internship Opportunity', new_internship_op_path %></li>
        <li><%= link_to 'New Content', contents_middle_path %></li>
        <li><%= link_to 'New Page', new_page_path %></li>
      </ul><br>
    </div>

    <div class="col-sm-9">
      <div class="list-group">
        <div class="list-group-item">
          <%= form_with(model: module_section) do |form| %>
          <% if module_section.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(module_section.errors.count, "error") %> prohibited this module_section from being saved:</h2>
              <ul>
                <% module_section.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="container">
            <p> </p>
            <form class="form-horizontal">
              <div class="form-group">
                <%= form.label :module_name, :class => "control-label col-sm-2" %>
                <div class="col-sm-4">
                  <%= form.text_field :module_name, :class => "form-control"%>
                </div>
              </div>
              <br>
              <br>
              <div class="form-group">        
                <div class="col-sm-offset-2 col-sm-10">
                  <%= form.submit "Submit", :class => "btn btn-default" %>
                </div>
              </div>
            </form>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

</body>
</html>

app/views/module_sections/edit.html.erb
<%= render 'form', module_section: @module_section %>

app/views/module_sections/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>Actions</h4>
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to 'New Module', new_module_section_path %></li>
        <li><%= link_to 'New Internship Opportunity', new_internship_op_path %></li>
        <li><%= link_to 'New Content', contents_path %></li>
        <li><%= link_to 'New Page', new_page_path %></li>
        <li><%= link_to 'View All Pages', pages_path %></li>
        <li><%= link_to 'Password Management', password_management_path %></li>
        <% if user_signed_in? %>
        Logged in as <strong><%= current_user.username %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% end %>
        
      </ul><br>
      
    </div>

    <div class="col-sm-9">
    <p id="notice"><%= notice %></p>
    <div class="list-group">
      <% @module_sections.each do |module_section| %>
        <div class="list-group-item">
          <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= module_section.module_name %></h3>
          </div>
          <div class="panel-body">
          <tr>
                <td><%= link_to 'Show', module_section %></td>
                <td><%= link_to 'Edit', edit_module_section_path(module_section) %></td>
                <td><%= link_to 'Destroy', module_section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          </div>
        </div>
        </div>
      <% end %>
    </div>
    </div>
  </div>
</div>

<footer class="container-fluid">
  <p>Footer Text</p>
</footer>

<br>

<%= link_to 'New Internship Opportunity', new_internship_op_path %>

<br>

<%= link_to 'New Page', new_page_path %>

<br>

<%= link_to 'New Content', contents_path %>

<br>

<%= link_to 'Users', users_index_path %>

<br>
<%end %>
<%= link_to 'View All Pages', pages_path %>

<br>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.username %></strong>.|
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>

app/views/module_sections/new.html.erb
<%= render 'form', module_section: @module_section %>

<%= link_to 'Back', module_sections_path %>

app/views/module_sections/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>
<body>
  <div class="container-fluid">
    <div class="row content">
      <%if current_user.admin? || current_user.root? %>
          <div class="col-sm-3 sidenav">
            <h4><%= link_to 'TAMU-FUSE', module_sections_path %></h4>
            <div class="panel panel-success">
              <div class="panel-heading">
                <% if user_signed_in? %>
                  Logged in as <strong><%= current_user.username %></strong>.|
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
                <% end %>
              </div>
              <div class = "panel-body">
                <%= link_to ' View All Modules', module_sections_path %> 
                <br>
                <%= link_to ' View All Pages', pages_path %> 
                <br>
                <% if current_user.admin? || current_user.root?  %>
                    <%= link_to ' View All Content', contents_path %> 
                    <br>
                    <%= link_to ' View All Internships', internship_ops_path %>
                  <%else%>
                    <%= link_to ' Internships Opportunities ', internship_ops_path %>
                <%end %>
                <% if current_user.root? %>
                  <br>
                  <%= link_to 'Manage Users', users_index_path %>
                <%end %>
              </div>
            </div>
            <ul class="nav nav-pills nav-stacked">
              <li><%= link_to 'New Module', new_module_section_path %></li>
              <li><%= link_to 'New Internship Opportunity', new_internship_op_path %></li>
              <li><%= link_to 'New Content', contents_middle_path %></li>
              <li><%= link_to 'New Page', new_page_path %></li>
            </ul><br>
          </div>

          <div class="col-sm-9">
            <p id="notice"><%= notice %></p>
              <div class="container">
                <p>
                  <strong>Module name:</strong>
                  <%= @module_section.module_name %>
                </p>
                <% if @module_section.module_name == "Internship Opportunities" %>
                  <table>
                    <thead>
                      <tr>
                        <th>Internship name</th>
                        <th>Company name</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @internship_ops.each do |internship_op| %>
                        <tr>
                          <td><%= internship_op.internship_name %></td>
                          <td><%= internship_op.company_name %></td>
                          <td><%= link_to 'Show', internship_op %></td>
                          <td><%= link_to 'Edit', edit_internship_op_path(internship_op) %></td>
                          <td><%= link_to 'Destroy', internship_op, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>

                <% else %>

                  <table class = "table">
                    <thead>
                      <tr>
                        <th>Module</th>
                        <th>Content</th>
                        <th>Page name</th>
                        <th>Page description</th>
                        <th colspan="3"></th>
                      </tr>
                    </thead>

                    <tbody>
                      <% @pages.try(:each) do |page| %>
                        <tr>
                          <% if page.module_name == @module_section.module_name %>
                              <td><%= @module_section.module_name %></td>
                              <td><%= page.content_ids %></td>
                              <td><%= page.page_name %></td>
                              <td><%= page.page_description %></td>
                              <td><%= link_to 'Show', page %></td>
                              <td><%= link_to 'Edit', edit_page_path(page) %></td>
                              <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          <% end %>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                <% end %>
                <%= link_to 'Edit', edit_module_section_path(@module_section) %>
              </div>
          </div>
        <%else%> 
          <div class="col-sm-3 sidenav">
            <h4><%= link_to 'TAMU-FUSE', module_sections_path %></h4>
            <div class="panel panel-success">
              <div class="panel-heading">
                <% if user_signed_in? %>
                  Logged in as <strong><%= current_user.username %></strong>.|
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
                <% end %>
              </div>
              <div class = "panel-body">
                <%= link_to ' View All Modules', module_sections_path %> 
                <br>
                <%= link_to ' View All Pages', pages_path %> 
                <br>
                <%= link_to ' Internships Opportunities ', internship_ops_path %> 
              </div>
            </div>
            <ul class="nav nav-pills nav-stacked">
              <% @pages.try(:each) do |page| %>
                <% if page.module_name == @module_section.module_name %>
                    <li><%= link_to page.page_name , page %></li>
                <% end %>
              <% end %>
            </ul><br>
          </div>

          <div class="col-sm-9">
            <p id="notice"><%= notice %></p>
              <div class="container">
                <div class="panel panel-success">
                  <div class="panel-heading">
                    <h3 class="panel-title"> Welcome to <%= @module_section.module_name %></h3>
                  </div>
                </div>
                <p>
                  <div class="panel-body">
                    <p>Please click a page on the left to view its content.</p>
                  </div>
                </p>
              </div>
          </div>
      <%end%>
    </div> 
  </div>
</body>
</html>