config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  resources :users
  resources :internship_ops
  resources :internships
  resources :module_sections
  resources :content_tags
  resources :tags
  resources :pages
  resources :contents, only: [:index, :new, :create, :destroy, :edit]
  resources :modules
  get '/contents/middle', to: 'contents#middle'
  get '/contents/callback', to: 'contents#callback'
  root 'module_sections#index' 
  get 'contents/index'
  get 'contents/new'
  get 'contents/create'
  get 'contents/destroy'
  get 'contents/:id', to: 'contents#edit'
  patch 'contents/:id', to: 'contents#update'
  get '/contents', to: 'contents#index'
  patch 'module_sections/:id', to: 'module_sections#update'
  get 'password_management', to: 'password_management#index'
  get 'password_management/:id', to: 'password_management#edit'
  patch 'password_management/:id', to: 'password_management#update'
  get 'users/index', to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/content.rb
class Content < ApplicationRecord
    before_validation(on: :create) do
        self.session_token ||= SecureRandom.hex
    end
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
    validates :title, :description, :content_type, presence: true # Make sure the owner's name is present.
end

app/controllers/contents_controller.rb
require 'google/apis/youtube_v3'
require 'google/api_client/client_secrets'
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show update edit destroy ]
  before_action :check_admin, only: %i[edit create update destroy]

  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  def middle
    redirect_to '/contents/new'
    #redirect_to auth_client.authorization_uri.to_s
    #ADD TAGS AS A PARAM FOR CONTENT OBJECT WHEN MOVE OVER 
  end

  # GET /contents/1 or /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)
    if @content.save
      redirect_to contents_path, notice: "Successfully uploaded."   
    else   
      render "new"   
    end 
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to contents_path, notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #Oauth stuff
  def callback
    auth_client.code = params[:code]
    auth_client.fetch_access_token!
    auth_client.client_secret = nil

    #store the auth client creds in the db
    session[:credentials] = auth_client.to_json

    redirect_to '/contents/new'
  end

  def auth_client
    @_auth_client ||= begin
        client_secrets = Google::APIClient::ClientSecrets.new(
            {
              "web": {
                  "client_id": Rails.application.credentials.dig(:youtube, :client_id),
                  "project_id": "tamu-fuse-media-hosting",
                  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                  "token_uri": "https://oauth2.googleapis.com/token",
                  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth/v1/certs",
                  "client_secret": Rails.application.credentials.dig(:youtube, :client_secret),
                  "redirect_uris": [
                      redirect_uri
                  ]
                }
            }
        )
        auth_client = client_secrets.to_authorization
        auth_client.update!(
            scope: 'https://www.googleapis.com/auth/youtube.force-ssl',
            redirect_uri: redirect_uri, 
            additional_parameters: {
                access_type: 'offline',
                include_granted_scopes: true,
            }
        )
        auth_client
    end
  end
  
  def redirect_uri
    #'http://localhost:3000/contents/callback'
    'https://stage-test-tamu-fuse.herokuapp.com/contents/callback'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id]) 
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:content_type, :title, :description, :attachment)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_form.html.erb
<%= form_with(model: content) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content_type %>
    <%= form.text_field :content_type %>
  </div>

  <div class="field">
    <%= form.label :attachment_url %>
    <%= form.text_field :attachment_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4><%= link_to 'TAMU-FUSE', module_sections_path %></h4> 
      <div class="panel panel-success">
        <div class="panel-heading">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.username %></strong>.|
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
          <% end %>
        </div>
        <div class = "panel-body">
          <%= link_to ' View All Modules', module_sections_path %> 
          <br>
          <%= link_to ' View All Pages', pages_path %> 
          <br>
          <% if current_user.admin? || current_user.root? %>
              <%= link_to ' View All Content', contents_path %> 
              <br>
              <%= link_to ' View All Internships', internship_ops_path %>
            <%else%>
              <%= link_to ' Internships Opportunities ', internship_ops_path %>
          <%end %>
          <% if current_user.root? %>
            <br>
            <%= link_to 'Manage Users', users_index_path %>
          <%end %>
        </div>
      </div>
      <ul class="nav nav-pills nav-stacked">
      <% if current_user.admin? || current_user.root? %>
        <li><%= link_to 'New Module', new_module_section_path %></li>
        <li><%= link_to 'New Internship Opportunity', new_internship_op_path %></li>
        <li><%= link_to 'New Content', contents_middle_path %></li>
        <li><%= link_to 'New Page', new_page_path %></li>
        <%end %>
        <% if current_user.root? %>
        <%= link_to 'Users', users_index_path %>
        <%end %>
        
      </ul>
      <br>
    </div>

    <div class="col-sm-9">
        <p id="notice"><%= notice %></p>
        <div class="container">
            <%= form_for @content, html: { multipart: true } do |f| %>   
                <form class="form-horizontal">
                    <div class="form-group">
                        <%= f.label :title, :class => "control-label col-sm-2" %>
                        <div class="col-sm-4">
                        <%= f.text_field :title, :class => "form-control"%>
                        </div>
                    </div>
                    <br>
                    <br>
                    <div class="form-group">
                        <%= f.label :description, :class => "control-label col-sm-2" %>
                        <div class="col-sm-4">
                        <%= f.text_field :description, :class => "form-control"%>
                        </div>
                    </div>
                    <br>
                    <br>
                    <div class="form-group">
                        <%= f.label :attachment, :class => "control-label col-sm-2" %>
                        <div class="col-sm-4">
                        <%= f.file_field :attachment%>
                        </div>
                    </div>
                    <br>
                    <br>
                    <div class="form-group">
                        <%= f.label :content_type, :class => "control-label col-sm-2" %>
                        <div class="col-sm-4">
                        <%= f.text_field :content_type, :class => "form-control"%>
                        </div>
                    </div>
                    <br>
                    <br>
                    <div class="form-group">        
                        <div class="col-sm-offset-2 col-sm-10">
                        <%= f.submit "Submit", :class => "btn btn-default" %>
                        </div>
                    </div>
                </form> 
            <% end %>
            <%= link_to 'Back', contents_path %>
        </div>
      
    </div>
  
  </div>
</div>

</body>
</html>

app/views/contents/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>
<body>
  <div class="container-fluid">
    <div class="row content">
      <%if current_user.admin? || current_user.root? %>
        <div class="col-sm-3 sidenav">
          <h4><%= link_to 'TAMU-FUSE', module_sections_path %></h4>
          <div class="panel panel-success">
            <div class="panel-heading">
              <% if user_signed_in? %>
                Logged in as <strong><%= current_user.username %></strong>.|
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
              <% end %>
            </div>
            <div class = "panel-body">
              <%= link_to ' View All Modules', module_sections_path %> 
              <br>
              <%= link_to ' View All Pages', pages_path %> 
              <br>
              <% if current_user.admin? || current_user.root? %>
                  <%= link_to ' View All Content', contents_path %> 
                  <br>
                  <%= link_to ' View All Internships', internship_ops_path %>
                <%else%>
                  <%= link_to ' Internships Opportunities ', internship_ops_path %>
              <%end %>
              <% if current_user.root? %>
                <br>
                <%= link_to 'Manage Users', users_index_path %>
              <%end %>
            </div>
          </div>
          <ul class="nav nav-pills nav-stacked">
            <li><%= link_to 'New Module', new_module_section_path %></li>
            <li><%= link_to 'New Internship Opportunity', new_internship_op_path %></li>
            <li><%= link_to 'New Content', contents_middle_path %></li>
            <li><%= link_to 'New Page', new_page_path %></li> 
          </ul><br>
        </div>

        <div class="col-sm-9">
          <div class= "container">
            <h4>Contents | <%= link_to 'New Content', contents_middle_path %></h4>
              <table class="table">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Content ID</th>
                    <th>Content Type</th>
                    <th>Actions</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                  <% @contents.try(:each) do |content| %>
                    <tr>
                      <td><%= content.title %></td> 
                      <td><%= content.contentID %></td>
                      <td><%= content.content_type %></td>
                      <td><%= link_to "Download", content.attachment_url %></td>   
                      <td><%= link_to 'Edit', edit_content_path(content) %></td>
                      <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <br>
          </div>
        </div>
        <%else%> 
          <p>admin only</p>
      <%end%>
    </div> 
  </div>
</body>
</html>

app/views/contents/middle.html.erb
<h1>"Middle Man!"</h1>

app/views/contents/new.html.erb
</div>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
    .row.content {height: 1500px}
    
    /* Set gray background color and 100% height */
    .sidenav {
      background-color: #f1f1f1;
      height: 100%;
    }
    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height: auto;} 
    }
  </style>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4><%= link_to 'TAMU-FUSE', module_sections_path %></h4>
      <div class="panel panel-success">
        <div class="panel-heading">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.username %></strong>.|
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
          <% end %>
        </div>
        <div class = "panel-body">
          <%= link_to ' View All Modules', module_sections_path %> 
          <br>
          <%= link_to ' View All Pages', pages_path %> 
          <br>
          <% if current_user.admin? || current_user.root? %>
              <%= link_to ' View All Content', contents_path %> 
              <br>
              <%= link_to ' View All Internships', internship_ops_path %>
            <%else%>
              <%= link_to ' Internships Opportunities ', internship_ops_path %>
          <%end %>
          <% if current_user.root? %>
            <br>
            <%= link_to 'Manage Users', users_index_path %>
          <%end %>
        </div>
      </div>
      <ul class="nav nav-pills nav-stacked">
        <li><%= link_to 'New Module', new_module_section_path %></li>
        <li><%= link_to 'New Internship Opportunity', new_internship_op_path %></li>
        <li><%= link_to 'New Content', contents_middle_path %></li>
        <li><%= link_to 'New Page', new_page_path %></li>
        
        
      </ul><br>
      
    </div>

    <div class="col-sm-9">
      <div class="list-group">
        <div class="list-group-item">
            <div class="container">
                <%= form_for @content, html: { multipart: true } do |f| %>   
                    <form class="form-horizontal">
                        <div class="form-group">
                            <%= f.label :title, :class => "control-label col-sm-2" %>
                            <div class="col-sm-4">
                            <%= f.text_field :title, :class => "form-control"%>
                            </div>
                        </div>
                        <br>
                        <br>
                        <div class="form-group">
                            <%= f.label :description, :class => "control-label col-sm-2" %>
                            <div class="col-sm-4">
                            <%= f.text_field :description, :class => "form-control"%>
                            </div>
                        </div>
                        <br>
                        <br>
                        <div class="form-group">
                            <%= f.label :attachment, :class => "control-label col-sm-2" %>
                            <div class="col-sm-4">
                            <%= f.file_field :attachment%>
                            </div>
                        </div>
                        <br>
                        <br>
                        <div class="form-group">
                            <%= f.label :content_type, :class => "control-label col-sm-2" %>
                            <div class="col-sm-4">
                            <%= f.text_field :content_type, :class => "form-control"%>
                            </div>
                        </div>
                        <br>
                        <br>
                        <div class="form-group">        
                            <div class="col-sm-offset-2 col-sm-10">
                            <%= f.submit "Submit", :class => "btn btn-default" %>
                            </div>
                        </div>
                    </form> 
                <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid">
  <p>Footer Text</p>
</footer>

</body>
</html>

app/views/contents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @content.content_id %>
</p>

<p>
  <strong>Content type:</strong>
  <%= @content.content_type %>
</p>

<p>
  <strong>Content Link:</strong>
  <%= @content.attachment_url %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', contents_path %>