config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_prefix => 'my'
  resources :users
  resources :internship_ops
  resources :internships
  resources :module_sections
  resources :content_tags
  resources :tags
  resources :pages
  resources :contents, only: [:index, :new, :create, :destroy, :edit]
  resources :modules
  get '/contents/middle', to: 'contents#middle'
  get '/contents/callback', to: 'contents#callback'
  root 'module_sections#index' 
  get 'contents/index'
  get 'contents/new'
  get 'contents/create'
  get 'contents/destroy'
  get 'contents/:id', to: 'contents#edit'
  patch 'contents/:id', to: 'contents#update'
  get '/contents', to: 'contents#index'
  patch 'module_sections/:id', to: 'module_sections#update'
  get 'password_management', to: 'password_management#index'
  get 'password_management/:id', to: 'password_management#edit'
  patch 'password_management/:id', to: 'password_management#update'
  get 'users/index', to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
    before_validation(on: :create) do
        self.session_token ||= SecureRandom.hex
    end
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
    validates :title, :description, :content_type, presence: true # Make sure the owner's name is present.
end

app/models/content_tag.rb
class ContentTag < ApplicationRecord
    belongs_to :tag
    belongs_to :page
end

app/models/internship.rb
class Internship < ApplicationRecord
end

app/models/internship_op.rb
class InternshipOp < ApplicationRecord
end

app/models/module.rb
class Module < ApplicationRecord
end

app/models/module_section.rb
class ModuleSection < ApplicationRecord

    has_many :pages

    validates :module_name, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
    has_many :content_tags, dependent: :destroy
    has_many :tags, through: :content_tags

    validates :page_name, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :content_tags, dependent: :destroy
    has_many :pages, through: :content_tag
    validates :tag_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :authentication_keys => [:username]

  enum role: [:member, :admin, :root]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :member
  end
  
end

app/models/video.rb
class Video < ApplicationRecord
end

app/models/video_file.rb
class VideoFile < ApplicationRecord
    before_validation(on: :create) do
        self.session_token ||= SecureRandom.hex
    end
    mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.   
    validates :title, :description, presence: true # Make sure the owner's name is present.
    
end

app/models/youtube_session.rb
class YoutubeSession < ApplicationRecord
    before_validation(on: :create) do
        self.session_token ||= SecureRandom.hex
    end
end

app/controllers/content_tags_controller.rb
class ContentTagsController < ApplicationController
  before_action :set_content_tag, only: %i[ show edit update destroy ]
  before_action :check_admin, only: %i[edit create update destroy]

  # GET /content_tags or /content_tags.json
  def index
    @content_tags = ContentTag.all
  end

  # GET /content_tags/1 or /content_tags/1.json
  def show
  end

  # GET /content_tags/new
  def new
    @content_tag = ContentTag.new
  end

  # GET /content_tags/1/edit
  def edit
  end

  # POST /content_tags or /content_tags.json
  def create
    @content_tag = ContentTag.new(content_tag_params)

    respond_to do |format|
      if @content_tag.save
        format.html { redirect_to content_tag_url(@content_tag), notice: "Content tag was successfully created." }
        format.json { render :show, status: :created, location: @content_tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /content_tags/1 or /content_tags/1.json
  def update
    respond_to do |format|
      if @content_tag.update(content_tag_params)
        format.html { redirect_to content_tag_url(@content_tag), notice: "Content tag was successfully updated." }
        format.json { render :show, status: :ok, location: @content_tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content_tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_tags/1 or /content_tags/1.json
  def destroy
    @content_tag.destroy

    respond_to do |format|
      format.html { redirect_to content_tags_url, notice: "Content tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content_tag
      @content_tag = ContentTag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_tag_params
      params.require(:content_tag).permit(:contentTag_id, :tag_id, :content_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_tags_helper.rb
module ContentTagsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/internships_helper.rb
module InternshipsHelper
end

app/helpers/modules_helper.rb
module ModulesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/video_files_helper.rb
module VideoFilesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/content_tags/_form.html.erb
<%= form_with(model: content_tag) do |form| %>
  <% if content_tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(content_tag.errors.count, "error") %> prohibited this content_tag from being saved:</h2>

      <ul>
        <% content_tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :contentTag_id %>
    <%= form.number_field :contentTag_id %>
  </div>

  <div class="field">
    <%= form.label :tag_id %>
    <%= form.number_field :tag_id %>
  </div>

  <div class="field">
    <%= form.label :content_id %>
    <%= form.number_field :content_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/content_tags/edit.html.erb
<h1>Editing Content Tag</h1>

<%= render 'form', content_tag: @content_tag %>

<%= link_to 'Show', @content_tag %> |
<%= link_to 'Back', content_tags_path %>

app/views/content_tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Content Tags</h1>

<table>
  <thead>
    <tr>
      <th>Contenttag</th>
      <th>Tag</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @content_tags.each do |content_tag| %>
      <tr>
        <td><%= content_tag.contentTag_id %></td>
        <td><%= content_tag.tag_id %></td>
        <td><%= content_tag.content_id %></td>
        <td><%= link_to 'Show', content_tag %></td>
        <td><%= link_to 'Edit', edit_content_tag_path(content_tag) %></td>
        <td><%= link_to 'Destroy', content_tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Content Tag', new_content_tag_path %>

app/views/content_tags/new.html.erb
<h1>New Content Tag</h1>

<%= render 'form', content_tag: @content_tag %>

<%= link_to 'Back', content_tags_path %>

app/views/content_tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contenttag:</strong>
  <%= @content_tag.contentTag_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @content_tag.tag_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @content_tag.content_id %>
</p>

<%= link_to 'Edit', edit_content_tag_path(@content_tag) %> |
<%= link_to 'Back', content_tags_path %>